on:
  push:
    branches:
      - backEnd

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 私钥
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      # 用户名
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      # 主机地址
      SSH_HOST: ${{ secrets.SSH_HOST }}
      # 指纹
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOST }}
      #密码
      SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd Desktop\Bookstore-backstage
            git pull
            npx prisma db push
            npm run build
            pm2 restart app



            
